apiVersion: v1

kind: Service

metadata:
  name: web-app
  namespace: project1

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP

  selector:
    app: web-app
